import {
  Building2,
  FileText,
  HelpCircle,
  Images,
  Info,
  Layers,
  LayoutList,
  LayoutDashboard,
  LayoutGrid,
  ListOrdered,
  Mail,
  Megaphone,
  Menu,
  MessageSquare,
  Package,
  Paintbrush,
  Palette,
  PenLine,
  Plus,
  Search,
  Settings,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tags,
  Ticket,
  UserRound,
  Users,
  type LucideIcon,
} from "lucide-react";

export const navigationIcons: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  products: Package,
  allProducts: Package,
  productAttributes: LayoutList,
  productBrands: Building2,
  productSettings: SlidersHorizontal,
  addProduct: Plus,
  orders: ShoppingCart,
  allOrders: ListOrdered,
  users: Users,
  allUsers: UserRound,
  coupons: Ticket,
  context: Layers,
  contextOverview: LayoutGrid,
  hero: Sparkles,
  productSlides: Images,
  proBanners: Megaphone,
  brands: Building2,
  customerReviews: Star,
  faq: HelpCircle,
  contextContactUs: Mail,
  navigation: Menu,
  weblog: FileText,
  allPosts: FileText,
  addPost: PenLine,
  postCategories: Tags,
  comments: MessageSquare,
  themes: Palette,
  setStyle: Paintbrush,
  seo: Search,
  generalSetting: Settings,
  baseInformation: Info,
  contactComments: MessageSquare,
};

export function getNavIcon(nameKey: string): LucideIcon {
  return navigationIcons[nameKey] ?? LayoutGrid;
}
