import {
  BadgePercent,
  BookOpenText,
  Boxes,
  CirclePlus,
  CreditCard,
  FilePenLine,
  FolderKanban,
  GalleryHorizontalEnd,
  Gauge,
  Globe2,
  HelpCircle,
  Images,
  Inbox,
  LayoutTemplate,
  Mail,
  Megaphone,
  MessageCircleMore,
  Package2,
  PanelsTopLeft,
  ReceiptText,
  Settings2,
  Shapes,
  Sparkles,
  SquareStack,
  Star,
  Store,
  SwatchBook,
  Tags,
  UserRound,
  UsersRound,
  WandSparkles,
  type LucideIcon,
} from "lucide-react";

/**
 * Premium SaaS icon set — distinctive Lucide glyphs, stroke 1.5 in UI
 */
export const navigationIcons: Record<string, LucideIcon> = {
  dashboard: Gauge,
  products: Boxes,
  allProducts: Package2,
  productAttributes: Shapes,
  productBrands: Store,
  productSettings: Tags,
  addProduct: CirclePlus,
  orders: CreditCard,
  allOrders: ReceiptText,
  users: UsersRound,
  allUsers: UserRound,
  coupons: BadgePercent,
  context: SquareStack,
  contextOverview: PanelsTopLeft,
  hero: Sparkles,
  productSlides: GalleryHorizontalEnd,
  proBanners: Megaphone,
  brands: Store,
  customerReviews: Star,
  faq: HelpCircle,
  contextContactUs: Mail,
  navigation: LayoutTemplate,
  weblog: BookOpenText,
  allPosts: BookOpenText,
  addPost: FilePenLine,
  postCategories: Tags,
  comments: MessageCircleMore,
  themes: SwatchBook,
  setStyle: WandSparkles,
  seo: Globe2,
  generalSetting: Settings2,
  baseInformation: Inbox,
  contactComments: MessageCircleMore,
};

export function getNavIcon(nameKey: string): LucideIcon {
  return navigationIcons[nameKey] ?? FolderKanban;
}
